### ISSUE TITLE
addMapping check for just one ERC20 to one ESDT

### ISSUE THREAD

**Issue by mihaieremia** [ElrondNetwork/sc-bridge-elrond#47]
We should allow just one ERC20 to one ESDT and not many ERC20 to one ESDT :)
https://github.com/ElrondNetwork/sc-bridge-elrond/blob/5d9fc4c273da93b678a81579a19a369a5b4b0176/multisig/src/setup.rs#L241

**Comment by dorin-iancu** [comment]
Solved in PR  #48
